import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
      },
      header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
      },
      backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#432272',
        alignItems: 'center',
        justifyContent: 'center',
      },
      backButtonText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#432272',
      },
      placeholder: {
        width: 40,
      },
      scrollView: {
        flex: 1,
      },
      filtersContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#f8f9fa',
        margin: 16,
        borderRadius: 12,
      },
      dropdownContainer: {
        flex: 1,
        marginRight: 16,
        position: 'relative',
        marginBottom: 8,
      },
      dropdownButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
      },
      dropdownButtonText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
      },
      dropdownLabel: {
        fontSize: 16,
        color: '#000000',
        marginBottom: 6,
        marginLeft: 4,
      },
      dropdownArrow: {
        fontSize: 12,
        color: '#666',
      },
      moreFiltersContainer: {
        marginTop: 12,
        flexDirection: 'row',
        justifyContent: 'space-evenly',
      },
      resetButton: {
        backgroundColor: '#eee',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        borderColor: '#432272',
        borderWidth: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      moreFiltersActiveButton: {
        backgroundColor: '#432272',
      },
      moreFiltersActiveText: {
        color: '#fff',
        fontWeight: '600',
      },
      resetButtonText: {
        color: '#333',
        fontSize: 14,
        fontWeight: '400',
      },
      dropdownMenu: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        marginTop: 4,
        zIndex: 1000,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      subcategoryItem: {
        paddingLeft: 32,
        paddingRight: 16,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f6f6f6',
        backgroundColor: '#fafafa',
      },
      subcategoryItemText: {
        fontSize: 15,
        color: '#444',
      },
      dropdownItem: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
      },
      dropdownItemText: {
        fontSize: 16,
        color: '#333',
      },
      selectedItem: {
        color: '#432272',
        fontWeight: 'bold',
      },
      emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 50,
      },
      emptyStateText: {
        fontSize: 18,
        color: '#666',
        textAlign: 'center',
      },
      elementsContainer: {
        paddingHorizontal: 20,
        gap: 10,
      },
      elementContainer: {
        flexDirection: 'column',
        backgroundColor: '#f8f9fa',
        alignItems: 'center',
        width: '100%',
        borderRadius: 10,
      },
      elementItem: {
        flexDirection: 'row',
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        padding: 6,
        marginBottom: 2,
        alignItems: 'flex-start',
      },
      elementImage: {
        width: 75,
        height: 75,
        borderRadius: 8,
        marginRight: 20,
        marginLeft: 2,
      },
      elementContent: {
        flex: 1,
      },
      elementTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 15,
        textAlign: 'right',
      },
      elementList: {
        marginTop: 10,
        marginLeft: 10,
      },
      listItem: {
        flexDirection: 'row',
        marginBottom: 8,
      },
       bulletPoint: {
        fontSize: 14,
        color: '#432272',
        marginRight: 10,
        marginLeft: 12,
        marginTop: 0,
      },
      listItemText: {
        flex: 1,
        fontSize: 15,
        color: '#4c4c4c',
        lineHeight: 20,
        marginRight: 20,
      },
      listLocation: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        width: '100%',
        marginTop: 8,
        marginBottom: 16,
      },
      listLocationText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
      },
      bulletIcon: {
        width: 16,
        height: 20,
        marginRight: 10,
        alignItems: 'center',
        justifyContent: 'center',
      },
      remoteTag: {
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: 14,
        backgroundColor: '#432272',
        opacity: 0.95,
      },
      remoteTagText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '700',
      },
      // Modal Styles
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalContainer: {
        backgroundColor: '#fff',
        borderRadius: 20,
        height: '80%',
        maxHeight: '80%',
        width: '90%',
        paddingBottom: 0,
      },
      modalScrollView: {
        flex: 1,
        maxHeight: '100%',
      },
      modalScrollContent: {
        paddingTop: 20,
        paddingBottom: 20,
      },
      modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
      },
      modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#432272',
      },
      modalContent: {
        flex: 1,
        minHeight: 0,
        paddingHorizontal: 20,
      },
      modalResetButton: {
        alignSelf: 'flex-end',
        backgroundColor: '#f2f2f2',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 8,
        marginVertical: 8,
      },
      modalResetText: {
        fontSize: 12,
        color: '#333',
        fontWeight: '600',
      },
      modalSectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#432272',
        marginTop: 16,
        marginBottom: 6,
      },
      modalEmptyText: {
        fontSize: 14,
        color: '#666',
        fontStyle: 'italic',
        marginBottom: 16,
      },
      checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
      },
      checkboxBox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: '#ccc',
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
      },
      checkboxBoxChecked: {
        backgroundColor: '#432272',
        borderColor: '#432272',
      },
      checkboxLabel: {
        fontSize: 16,
        color: '#333',
        flex: 1,
      },
      cityPillsContainer: {
        marginBottom: 16,
      },
      cityPillsLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
      },
      cityPillsScroll: {
        maxHeight: 50,
      },
      cityPill: {
        backgroundColor: '#f0f0f0',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
      },
      cityPillActive: {
        backgroundColor: '#432272',
      },
      cityPillText: {
        fontSize: 14,
        color: '#333',
        fontWeight: '500',
      },
      cityPillTextActive: {
        color: '#fff',
      },
      modalFooter: {
        flexDirection: 'row',
        justifyContent: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        backgroundColor: '#fff',
      },
      modalFooterButtonPrimary: {
        flex: 1,
        backgroundColor: '#432272',
        paddingVertical: 12,
        borderRadius: 8,
        marginHorizontal: 25,
        alignItems: 'center',
      },
      modalFooterButtonPrimaryText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
      },
});